#!/bin/bash
#
# kasutajate nimekiri kujul Perenimi, Eesnimi
#
#skripti algus
#
who | cut -f1 -d" " | cut -f2 -d"." > perenimi # lõikame perenime
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi # lõikame eesnime
paste -d"." perenimi eesnimi > nimed # kleebime need failid kokku
cat nimed | sort | uniq # sorteerime väljundi ja võtame korduvad välja
#
#skripti lõpp
